var api_url = "http://54.238.141.68:8090/apiv1/";
var params_arr = {
		  "av":"目前App版本的號碼 App Version",
		  "cc":"使用者手機國碼 Country Code",
		  "pn":"使用者手機號碼 Phone Number",
		  "em":"使用者電子郵件 User e-Mail",
		  "di":"裝置識別碼 Device Id",
		  "op":"一次性密碼 One-time Password",
		  "ui":"使用者識別碼 User Id, UuId",
		  "ul":"使用者列表 User List",
		  "at":"授權字串 Access Token",
		  "up":"使用者密碼 User Password",
		  "ul":"使用者列表 User List",
		  "ga":"團體 Avatar URL Group Avatar",
		  "gn":"團體名稱 Group Name",
		  "gd":"團體說明 Group Description",
		  "gl":"團體列表 Group List",
		  "gi":"團體 ID Group Id",
		  "gm":"團體登入識別碼 Group Identify mark",
		  "gp":"團體權限定義 Group permission define",
		  "gt":"團體內組織定義 Group Arch. item define.",
		  "pt":"推撥ID Push Token",
		  "mc":"通知中心 Message Center",
		  "um":"更版訊息 APP Upgrade Message",
		  "nk":"使用者暱稱 User Nick Name",
		  "it":"圖檔類別 Image Type",
		  "tn":"圖檔類別-小圖 Thumbnail",
		  "og":"圖檔類別-原圖 Original",
		  "sl":"個人狀態口號 Slogan",
		  "et":"授權終止時間 Expire Time",
		  "er":"錯誤訊息 Error Message",
		  "li":"i18n 語系代碼 Lang Id",
		  "ug":"更版旗標 APP Upgrade"
}
    
